name: Preview Build
on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn' 

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Publish Update to Tester
        run: eas update --branch preview --message "Auto-deploy via GitHub Actions"